enum AuthActionTypes {
  USER_LOGGED_IN = 'USER_LOGGED_IN_SUCCESS',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  LOADING = 'LOADING',
  ERROR = 'ERROR',
  USER_LOGGED_IN_ERROR = 'USER_LOGGED_IN_ERROR',
  USER_REG_ERROR = 'USER_REG_ERROR',
  USER_RESET_PASS_ERROR = 'USER_RESET_PASS_ERROR',
  SET_SIGNUP_DATA = 'SET_SIGNUP_DATA',
  WEIGHTIN_RESULTS = 'WEIGHTIN_RESULTS',
  SPLASH_SCREEN_LOADED = 'SPLASH_SCREEN_LOADED',
  SET_UNIT_PREFERENCE = 'SET_UNIT_PREFERENCE',
}

export default AuthActionTypes;
